import assert from 'node:assert/strict';
import {
  buildTrainerSnapshot,
  calculateTrainerCompletionReward,
  estimateMissionXp,
  type TrainerAchievementUnlock,
  type TrainerXpEvent,
} from '../src/services/studyTrainer';
import type { AnalyticsStore, StudyBlock, StudyPreferences, Subject, UserSettings } from '../src/types';

const now = new Date('2026-05-18T12:00:00-03:00');

const subject: Subject = {
  id: 'math',
  userId: 'user',
  name: 'Matematica',
  color: '#00B4FF',
  icon: 'calculator',
  priority: 8,
  difficulty: 7,
  targetHours: 4,
  completedHours: 0,
  totalHours: 0,
  sessionsCount: 0,
  averageScore: 0,
  isActive: true,
  createdAt: now,
  updatedAt: now,
};

const settings: UserSettings = {
  name: 'QA',
  email: 'qa@nexora.local',
  theme: 'dark',
  dailyGoalHours: 1,
  preferredStart: '08:00',
  preferredEnd: '12:00',
  maxBlockMinutes: 50,
  breakMinutes: 10,
  excludeDays: [],
  aiDifficulty: 'adaptive',
  focusMode: false,
  autoSchedule: true,
  smartBreaks: true,
  dailyReminder: true,
  streakReminder: true,
  achievementAlerts: true,
  weeklyReport: true,
  notificationsEnabled: false,
  notificationMinutesBefore: 15,
  notificationSoundEnabled: false,
  backlogReminderEnabled: false,
  allowSundayBacklog: false,
  dailyHoursByWeekday: {
    dom: 0,
    seg: 1,
    ter: 1,
    qua: 1,
    qui: 1,
    sex: 1,
    sab: 0,
  },
};

const prefs: StudyPreferences = {
  hoursPerDay: 1,
  daysOfWeek: [1, 2, 3, 4, 5],
  mode: 'exam',
  examDate: '2026-11-08',
};

const makeBlock = (overrides: Partial<StudyBlock> & Pick<StudyBlock, 'id'>): StudyBlock => ({
  id: overrides.id,
  userId: 'user',
  subjectId: subject.id,
  subject,
  date: overrides.date ?? now,
  startTime: overrides.startTime ?? '08:00',
  endTime: overrides.endTime ?? '08:40',
  durationMinutes: overrides.durationMinutes ?? 40,
  status: overrides.status ?? 'scheduled',
  isBreak: overrides.isBreak ?? false,
  isAutoGenerated: true,
  type: overrides.type ?? 'AULA',
  sessionType: overrides.sessionType ?? 'teoria',
  createdAt: now,
  updatedAt: now,
  completedAt: overrides.completedAt,
});

const analytics: AnalyticsStore = { daily: {} };
const xpEvents: TrainerXpEvent[] = [];
const achievements: TrainerAchievementUnlock[] = [];

assert.equal(estimateMissionXp(35), 25, 'XP should be 10 base + 15 for 35 minutes');

const scheduledBlock = makeBlock({ id: 'block-1', durationMinutes: 40 });
const completedBlock = { ...scheduledBlock, status: 'completed' as const, completedAt: now };
const blocksAfter = [completedBlock];
const analyticsAfter: AnalyticsStore = {
  daily: {
    '2026-05-18': {
      hours: 1,
      sessions: 1,
    },
  },
};

const reward = calculateTrainerCompletionReward({
  block: scheduledBlock,
  minutesSpent: 40,
  plannerBlocks: blocksAfter,
  analytics: analyticsAfter,
  subjects: [{ ...subject, totalHours: 1, completedHours: 1, sessionsCount: 1 }],
  studyPrefs: prefs,
  userSettings: settings,
  xpEvents,
  unlockedAchievements: achievements,
  now,
});

assert.equal(reward.xpEarned, 95, 'first completion should include task, daily goal and first achievement XP');
assert.equal(reward.events.some((event) => event.eventKey === 'task:block-1:complete'), true);
assert.equal(reward.events.some((event) => event.eventKey === 'daily-goal:2026-05-18'), true);
assert.equal(reward.newAchievements.some((achievement) => achievement.achievementId === 'first-study'), true);

const duplicateReward = calculateTrainerCompletionReward({
  block: scheduledBlock,
  minutesSpent: 40,
  plannerBlocks: blocksAfter,
  analytics: analyticsAfter,
  subjects: [{ ...subject, totalHours: 1, completedHours: 1, sessionsCount: 1 }],
  studyPrefs: prefs,
  userSettings: settings,
  xpEvents: reward.events,
  unlockedAchievements: reward.newAchievements,
  now,
});

assert.equal(duplicateReward.xpEarned, 0, 'same task cannot generate XP twice');

const snapshot = buildTrainerSnapshot({
  plannerBlocks: blocksAfter,
  analytics: analyticsAfter,
  subjects: [{ ...subject, totalHours: 1, completedHours: 1, sessionsCount: 1 }],
  studyPrefs: prefs,
  userSettings: settings,
  xpEvents: reward.events,
  unlockedAchievements: reward.newAchievements,
  now,
});

assert.equal(snapshot.dailyGoalCompleted, true);
assert.equal(snapshot.todayXp, 95);
assert.equal(snapshot.level, 1);
assert.equal(snapshot.levelTitle, 'Iniciante');

console.log('Gamification trainer tests passed');
