const { test, expect } = require('@playwright/test');

test.use({ baseURL: 'http://localhost:3000' });
test.describe.configure({ timeout: 180000 });

const SUBJECT = {
  id: 'qa-matematica',
  userId: 'qa-user',
  name: 'Matematica',
  color: '#00B4FF',
  icon: 'calculator',
  priority: 5,
  difficulty: 6,
  targetHours: 6,
  completedHours: 1.5,
  totalHours: 1.5,
  sessionsCount: 2,
  averageScore: 78,
  isActive: true,
  createdAt: '2026-05-18T00:00:00.000Z',
  updatedAt: '2026-05-18T00:00:00.000Z',
};

function makeBlock(overrides) {
  return {
    id: overrides.id,
    userId: 'qa-user',
    subjectId: overrides.isBreak ? 'break' : SUBJECT.id,
    subject: overrides.isBreak ? undefined : SUBJECT,
    date: overrides.date,
    startTime: overrides.startTime,
    endTime: overrides.endTime,
    durationMinutes: overrides.durationMinutes,
    status: overrides.status || 'scheduled',
    isBreak: Boolean(overrides.isBreak),
    isAutoGenerated: true,
    originalDate: overrides.isBreak ? undefined : overrides.date,
    completedAt: overrides.completedAt,
    rescheduleCount: 0,
    type: overrides.type || (overrides.isBreak ? undefined : 'AULA'),
    sessionType: overrides.sessionType || (overrides.isBreak ? undefined : 'teoria'),
    description: overrides.description || (overrides.isBreak ? undefined : 'Aula + anotacoes + resumo'),
    createdAt: '2026-05-18T00:00:00.000Z',
    updatedAt: '2026-05-18T00:00:00.000Z',
  };
}

async function seedApp(page, theme) {
  await page.goto('/login', { waitUntil: 'domcontentloaded' });
  await page.evaluate((selectedTheme) => {
    const settings = {
      name: 'Estudante QA',
      email: 'qa@nexora.local',
      theme: selectedTheme,
      preferredStart: '08:00',
      preferredEnd: '12:00',
      dailyGoalHours: 4,
      maxBlockMinutes: 50,
      breakMinutes: 10,
      autoSchedule: true,
      smartBreaks: true,
      focusMode: false,
      aiDifficulty: 'medium',
      notificationsEnabled: false,
      notificationMinutesBefore: 15,
      notificationSoundEnabled: false,
      backlogReminderEnabled: false,
      allowSundayBacklog: false,
      excludeDays: [],
      dailyHoursByWeekday: {
        sun: 0,
        mon: 4,
        tue: 4,
        wed: 4,
        thu: 4,
        fri: 4,
        sat: 2,
      },
      dailyAvailabilityByWeekday: {
        mon: { start: '08:00', end: '12:00' },
        tue: { start: '08:00', end: '12:00' },
        wed: { start: '08:00', end: '12:00' },
        thu: { start: '08:00', end: '12:00' },
        fri: { start: '08:00', end: '12:00' },
        sat: { start: '09:00', end: '11:00' },
      },
    };

    const subject = JSON.parse(JSON.stringify(window.__QA_SUBJECT__));
    const blocks = JSON.parse(JSON.stringify(window.__QA_BLOCKS__));

    window.localStorage.clear();
    window.localStorage.setItem('nexora_theme', selectedTheme);
    window.localStorage.setItem('nexora_demo_session', 'true');
    window.localStorage.setItem(
      'nexora_demo_user',
      JSON.stringify({ email: 'qa@nexora.local', name: 'Estudante QA' })
    );
    window.localStorage.setItem('nexora_user_settings', JSON.stringify(settings));
    window.localStorage.setItem('nexora_subjects', JSON.stringify([subject]));
    window.localStorage.setItem('nexora_planner_blocks', JSON.stringify(blocks));
    window.localStorage.setItem(
      'nexora_study_prefs',
      JSON.stringify({
        hoursPerDay: 4,
        weeklyHours: 22,
        daysOfWeek: [1, 2, 3, 4, 5, 6],
        mode: 'exam',
        goal: 'enem',
        startDate: '2026-05-18',
        examDate: '2026-11-08',
        focusBlockMinutes: 50,
        blockDurationMinutes: 50,
        breakDurationMinutes: 10,
      })
    );
    window.localStorage.setItem(
      'nexora_analytics',
      JSON.stringify({
        daily: {
          '2026-05-18': {
            hours: 1.5,
            sessions: 2,
            focusScoreAvg: 82,
            productivityScoreAvg: 78,
            bySubject: { 'qa-matematica': { hours: 1.5, sessions: 2 } },
          },
        },
        subjectProfiles: {},
        sessionHistory: [],
      })
    );
    window.localStorage.setItem(
      'nexora_onboarding',
      JSON.stringify({ hasCompletedWelcome: true, hasCompletedTutorial: true })
    );
  }, theme);
}

async function auditPage(page, path) {
  await page.goto(path, { waitUntil: 'networkidle' });
  await page.waitForTimeout(350);
  const bodyText = await page.locator('body').innerText();
  const layout = await page.evaluate(() => ({
    overflowX: document.documentElement.scrollWidth > window.innerWidth + 8,
    blank: document.body.innerText.trim().length < 20,
  }));

  expect(bodyText).not.toMatch(/undefined|NaN|Invalid Date|\[object Object\]/i);
  expect(bodyText).not.toMatch(/Application error|Unhandled Runtime Error|TypeError|ReferenceError/i);
  expect(layout.overflowX).toBe(false);
  expect(layout.blank).toBe(false);
}

test.beforeEach(async ({ page }) => {
  await page.addInitScript(({ subject, blocks }) => {
    window.__QA_SUBJECT__ = subject;
    window.__QA_BLOCKS__ = blocks;
  }, {
    subject: SUBJECT,
    blocks: [
      makeBlock({
        id: 'qa-1',
        date: '2026-05-18T00:00:00.000Z',
        startTime: '08:00',
        endTime: '08:50',
        durationMinutes: 50,
        status: 'completed',
        completedAt: '2026-05-18T09:00:00.000Z',
      }),
      makeBlock({
        id: 'qa-break-1',
        date: '2026-05-18T00:00:00.000Z',
        startTime: '08:50',
        endTime: '09:00',
        durationMinutes: 10,
        isBreak: true,
      }),
      makeBlock({
        id: 'qa-2',
        date: '2026-05-18T00:00:00.000Z',
        startTime: '09:00',
        endTime: '09:50',
        durationMinutes: 50,
        type: 'EXERCICIOS',
        sessionType: 'pratica',
        description: 'Lista de exercicios + revisar erros',
      }),
      makeBlock({
        id: 'qa-3',
        date: '2026-05-19T00:00:00.000Z',
        startTime: '08:00',
        endTime: '08:50',
        durationMinutes: 50,
        type: 'REVISAO',
        sessionType: 'revisao',
        description: 'Revisao guiada com flashcards',
      }),
    ],
  });
});

test('public auth pages are stable on mobile and desktop', async ({ page }) => {
  const consoleProblems = [];
  page.on('console', (msg) => {
    const text = msg.text();
    if ((msg.type() === 'error' || msg.type() === 'warning') && !/favicon|DEP0205|scroll-behavior|sticky/i.test(text)) {
      consoleProblems.push(`${msg.type()}: ${text}`);
    }
  });

  for (const viewport of [
    { width: 390, height: 844 },
    { width: 1366, height: 768 },
  ]) {
    await page.setViewportSize(viewport);
    for (const path of ['/login', '/register', '/forgot-password', '/reset-password']) {
      await auditPage(page, path);
    }
  }

  await page.goto('/login', { waitUntil: 'networkidle' });
  await page.locator('input[name="email"]').fill('email-invalido');
  await page.locator('input[name="password"]').fill('');
  await page.locator('form button[type="submit"]').click();
  await expect(page.getByText(/Informe um e-mail valido/i)).toBeVisible();

  await page.goto('/forgot-password', { waitUntil: 'networkidle' });
  await page.locator('input[type="email"]').fill('qa@nexora.local');
  await page.locator('form button[type="submit"]').click();
  await expect(page.getByText(/recuperacao real depende/i)).toBeVisible();

  expect(consoleProblems).toEqual([]);
});

test('authenticated pages are stable in light and dark themes', async ({ page }) => {
  const consoleProblems = [];
  page.on('console', (msg) => {
    const text = msg.text();
    if ((msg.type() === 'error' || msg.type() === 'warning') && !/favicon|DEP0205|sticky/i.test(text)) {
      consoleProblems.push(`${msg.type()}: ${text}`);
    }
  });

  for (const theme of ['light', 'dark']) {
    await seedApp(page, theme);
    for (const viewport of [
      { width: 390, height: 844 },
      { width: 768, height: 1024 },
      { width: 1366, height: 768 },
    ]) {
      await page.setViewportSize(viewport);
      for (const path of ['/dashboard', '/planner', '/subjects', '/analytics', '/settings']) {
        await auditPage(page, path);
      }
    }
  }

  expect(consoleProblems).toEqual([]);
});
