/**
 * Testes da sincronização incremental (src/lib/syncDelta.ts).
 *
 * Usa um cliente Prisma em memória, então roda sem banco. Cobre os casos que
 * quebram na vida real:
 *  - conflito entre celular e computador (last-write-wins);
 *  - exclusão em um dispositivo propagando para o outro (tombstones);
 *  - bloco órfão (disciplina apagada) descartado em vez de estourar FK;
 *  - migração do blob antigo (localStorage serializado) para linhas;
 *  - leitura por cursor (delta) trazendo só o que mudou.
 *
 * Rodar com: npm run test:sync
 */

import assert from 'node:assert';
import { createMemoryClient } from './helpers/memoryPrisma';
import {
  applySyncDelta,
  getSyncCounts,
  mergeSnapshotDelta,
  migrateProgressSnapshot,
  readSyncDelta,
  type SyncClient,
} from '../src/lib/syncDelta';

const userId = 'user-1';
const otherUserId = 'user-2';

const subjectRecord = (overrides: Record<string, unknown> = {}) => ({
  id: 'sub-mat',
  userId,
  name: 'Matemática',
  color: '#00B4FF',
  icon: 'book',
  priority: 9,
  difficulty: 8,
  targetHours: 6,
  completedHours: 0,
  totalHours: 0,
  sessionsCount: 0,
  averageScore: 0,
  isActive: true,
  createdAt: '2026-09-01T10:00:00.000Z',
  updatedAt: '2026-09-01T10:00:00.000Z',
  deletedAt: null,
  ...overrides,
});

const blockRecord = (overrides: Record<string, unknown> = {}) => ({
  id: 'block-1',
  userId,
  subjectId: 'sub-mat',
  date: '2026-09-02T00:00:00.000Z',
  startTime: '09:00',
  endTime: '10:00',
  durationMinutes: 60,
  status: 'scheduled',
  isBreak: false,
  isAutoGenerated: true,
  rescheduleCount: 0,
  createdAt: '2026-09-01T10:00:00.000Z',
  updatedAt: '2026-09-01T10:00:00.000Z',
  ...overrides,
});

async function main() {
// ---------------------------------------------------------------------------
// 1. Push básico + leitura por cursor
// ---------------------------------------------------------------------------
{
  const { client } = createMemoryClient();

  const result = await applySyncDelta({
    userId,
    delta: { subjects: [subjectRecord()], blocks: [blockRecord()] },
    client,
  });

  assert.strictEqual(result.applied.subjects, 1, 'deve gravar a disciplina');
  assert.strictEqual(result.applied.blocks, 1, 'deve gravar o bloco');
  assert.strictEqual(result.droppedBlockIds.length, 0, 'não deve descartar bloco válido');

  const delta = await readSyncDelta({ userId, client: client as never });
  assert.strictEqual(delta.subjects.length, 1);
  assert.strictEqual(delta.blocks.length, 1);

  const cursor = String(delta.blocks[delta.blocks.length - 1].updatedAt);
  const incremental = await readSyncDelta({
    userId,
    since: { blocks: cursor },
    client: client as never,
  });
  assert.strictEqual(
    incremental.blocks.length,
    0,
    'cursor do servidor deve evitar reenvio de bloco inalterado'
  );

  const counts = await getSyncCounts(userId, client as never);
  assert.deepStrictEqual(counts, { subjects: 1, blocks: 1, sessions: 0 });
}

// ---------------------------------------------------------------------------
// 2. Conflito entre dispositivos: last-write-wins
// ---------------------------------------------------------------------------
{
  const { client } = createMemoryClient();

  await applySyncDelta({
    userId,
    delta: { subjects: [subjectRecord()], blocks: [blockRecord({ status: 'completed', updatedAt: '2026-09-02T12:00:00.000Z' })] },
    client,
  });

  // Computador com versão mais antiga (offline por horas) não pode sobrescrever o celular.
  const stale = await applySyncDelta({
    userId,
    delta: {
      blocks: [
        blockRecord({
          status: 'scheduled',
          updatedAt: '2026-09-01T11:00:00.000Z',
        }),
      ],
    },
    client,
  });
  assert.strictEqual(stale.applied.blocks, 0, 'versão antiga não deve sobrescrever');
  assert.strictEqual(stale.applied.skipped, 1, 'conflito deve ser contado como ignorado');

  const after = await readSyncDelta({ userId, client: client as never });
  assert.strictEqual(after.blocks[0].status, 'completed', 'estado mais recente deve permanecer');

  // Já uma alteração mais nova é aceita.
  const fresh = await applySyncDelta({
    userId,
    delta: { blocks: [blockRecord({ status: 'skipped', updatedAt: '2026-09-02T18:00:00.000Z' })] },
    client,
  });
  assert.strictEqual(fresh.applied.blocks, 1, 'versão mais nova deve vencer');

  const finalState = await readSyncDelta({ userId, client: client as never });
  assert.strictEqual(finalState.blocks[0].status, 'skipped');
}

// ---------------------------------------------------------------------------
// 3. Tombstone: exclusão em um dispositivo chega no outro
// ---------------------------------------------------------------------------
{
  const { client } = createMemoryClient();

  await applySyncDelta({ userId, delta: { subjects: [subjectRecord()] }, client });
  await applySyncDelta({
    userId,
    delta: { subjects: [subjectRecord({ deletedAt: '2026-09-03T09:00:00.000Z', updatedAt: '2026-09-03T09:00:00.000Z' })] },
    client,
  });

  const counts = await getSyncCounts(userId, client as never);
  assert.strictEqual(counts.subjects, 0, 'disciplina excluída não deve contar');

  const delta = await readSyncDelta({ userId, client: client as never });
  assert.strictEqual(delta.subjects.length, 1, 'o tombstone precisa ser enviado ao outro dispositivo');
  assert.ok(delta.subjects[0].deletedAt, 'tombstone deve conter deletedAt');
}

// ---------------------------------------------------------------------------
// 4. Bloco órfão (disciplina apagada) é descartado, não estoura FK
// ---------------------------------------------------------------------------
{
  const { client } = createMemoryClient();

  const result = await applySyncDelta({
    userId,
    delta: {
      subjects: [subjectRecord({ deletedAt: '2026-09-03T09:00:00.000Z', updatedAt: '2026-09-03T09:00:00.000Z' })],
      blocks: [blockRecord({ id: 'block-orfao' })],
    },
    client,
  });

  assert.deepStrictEqual(result.droppedBlockIds, ['block-orfao'], 'bloco órfão deve ser devolvido ao cliente');
  assert.strictEqual(result.applied.blocks, 0);

  const counts = await getSyncCounts(userId, client as never);
  assert.strictEqual(counts.blocks, 0);
}

// ---------------------------------------------------------------------------
// 4b. Apagar disciplina + blocos na mesma sincronização funciona
// ---------------------------------------------------------------------------
{
  const { client } = createMemoryClient();

  await applySyncDelta({
    userId,
    delta: { subjects: [subjectRecord()], blocks: [blockRecord(), blockRecord({ id: 'block-2' })] },
    client,
  });

  const result = await applySyncDelta({
    userId,
    delta: {
      subjects: [subjectRecord({ deletedAt: '2026-09-03T09:00:00.000Z', updatedAt: '2026-09-03T09:00:00.000Z' })],
      blocks: [
        blockRecord({ id: 'block-1', deletedAt: '2026-09-03T09:00:00.000Z', updatedAt: '2026-09-03T09:00:00.000Z' }),
        blockRecord({ id: 'block-2', deletedAt: '2026-09-03T09:00:00.000Z', updatedAt: '2026-09-03T09:00:00.000Z' }),
      ],
    },
    client,
  });

  assert.deepStrictEqual(
    result.droppedBlockIds,
    [],
    'apagar os blocos da disciplina apagada não pode ser tratado como órfão'
  );
  assert.strictEqual(result.applied.deleted, 3, 'disciplina + 2 blocos excluídos');

  const counts = await getSyncCounts(userId, client as never);
  assert.deepStrictEqual(counts, { subjects: 0, blocks: 0, sessions: 0 }, 'nada sobra no servidor');
}

// ---------------------------------------------------------------------------
// 4c. Tombstone de registro que nunca chegou ao servidor não cria fantasma
// ---------------------------------------------------------------------------
{
  const { client } = createMemoryClient();

  const result = await applySyncDelta({
    userId,
    delta: {
      subjects: [subjectRecord({ deletedAt: '2026-09-03T09:00:00.000Z', updatedAt: '2026-09-03T09:00:00.000Z' })],
      blocks: [blockRecord({ id: 'block-nunca-visto', deletedAt: '2026-09-03T09:00:00.000Z', updatedAt: '2026-09-03T09:00:00.000Z' })],
    },
    client,
  });

  const counts = await getSyncCounts(userId, client as never);
  assert.deepStrictEqual(counts, { subjects: 0, blocks: 0, sessions: 0 });
  assert.strictEqual(result.applied.deleted, 0, 'nada para excluir');
}

// ---------------------------------------------------------------------------
// 5. Isolamento por usuário
// ---------------------------------------------------------------------------
{
  const { client } = createMemoryClient();

  await applySyncDelta({ userId, delta: { subjects: [subjectRecord()] }, client });
  const intruder = await applySyncDelta({
    userId: otherUserId,
    delta: { blocks: [blockRecord({ id: 'block-x' })] },
    client,
  });
  assert.deepStrictEqual(
    intruder.droppedBlockIds,
    ['block-x'],
    'usuário não pode gravar bloco em disciplina de outro usuário'
  );
}

// ---------------------------------------------------------------------------
// 6. Migração do blob antigo (localStorage) para linhas
// ---------------------------------------------------------------------------
{
  const { client, snapshots } = createMemoryClient();

  snapshots.set(userId, {
    nexora_subjects: [subjectRecord()],
    nexora_planner_blocks: [
      blockRecord(),
      blockRecord({ id: 'block-2', isBreak: true, subjectId: 'break', startTime: '10:00', endTime: '10:10', durationMinutes: 10 }),
    ],
    nexora_analytics: { daily: { '2026-09-02': { hours: 1, sessions: 1 } } },
  });

  const migration = await migrateProgressSnapshot({ userId, client });
  assert.strictEqual(migration.migrated, true, 'deve migrar o blob antigo');
  assert.strictEqual(migration.subjects, 1);
  assert.strictEqual(migration.blocks, 2, 'blocos e intervalos devem ser migrados');

  const counts = await getSyncCounts(userId, client as never);
  assert.deepStrictEqual(counts, { subjects: 1, blocks: 2, sessions: 0 });

  const again = await migrateProgressSnapshot({ userId, client });
  assert.strictEqual(again.migrated, false, 'migração precisa ser idempotente');

  const afterMigration = await readSyncDelta({ userId, client: client as never });
  assert.strictEqual(afterMigration.blocks.length, 2, 'migração não pode duplicar blocos');

  // Analytics (não migrado) continua disponível no snapshot de compatibilidade.
  const snapshot = await client.userProgressSnapshot.findUnique({ where: { userId } });
  assert.ok(
    (snapshot?.payload as Record<string, unknown>).nexora_analytics,
    'chaves não migradas continuam no snapshot'
  );
}

// ---------------------------------------------------------------------------
// 7. Snapshot de compatibilidade: mesclagem por chave
// ---------------------------------------------------------------------------
{
  const { client, snapshots } = createMemoryClient();
  snapshots.set(userId, { nexora_analytics: { daily: {} }, nexora_onboarding: { step: 1 } });

  await mergeSnapshotDelta({
    userId,
    snapshots: { nexora_onboarding: { step: 3 }, nexora_study_prefs: { hoursPerDay: 5 } },
    client,
  });

  const payload = snapshots.get(userId)!;
  assert.deepStrictEqual(payload.nexora_onboarding, { step: 3 }, 'chave existente deve ser atualizada');
  assert.deepStrictEqual(payload.nexora_study_prefs, { hoursPerDay: 5 }, 'chave nova deve ser criada');
  assert.ok(payload.nexora_analytics, 'chaves não enviadas devem ser preservadas');
}

// ---------------------------------------------------------------------------
// 8. Volume: 1 ano de dados enviados em delta é ordens de grandeza menor
// ---------------------------------------------------------------------------
{
  const { client } = createMemoryClient();

  const yearSubjects = [subjectRecord()];
  const yearBlocks = Array.from({ length: 2400 }, (_, index) =>
    blockRecord({
      id: `block-${index}`,
      date: new Date(Date.UTC(2026, 0, 1 + (index % 365))).toISOString(),
      updatedAt: new Date(Date.UTC(2026, 0, 1 + (index % 365), 12, 0, 0)).toISOString(),
    })
  );

  const pushBytes = JSON.stringify({ subjects: yearSubjects, blocks: yearBlocks }).length;
  await applySyncDelta({ userId, delta: { subjects: yearSubjects, blocks: yearBlocks }, client });

  const fullRead = await readSyncDelta({ userId, client: client as never });
  const lastServerUpdatedAt = String(fullRead.blocks[fullRead.blocks.length - 1].updatedAt);
  const cursorRead = await readSyncDelta({
    userId,
    since: { blocks: lastServerUpdatedAt },
    client: client as never,
  });

  const fullBytes = JSON.stringify(fullRead).length;
  const cursorBytes = JSON.stringify(cursorRead).length;

  console.log(
    `Sync — carga de 1 ano: envio ${(pushBytes / 1024).toFixed(0)} KB, leitura completa ${(fullBytes / 1024).toFixed(0)} KB, leitura incremental ${cursorBytes} bytes`
  );

  assert.strictEqual(cursorRead.blocks.length, 0, 'sem mudanças, o delta é vazio');
  assert.ok(cursorBytes < 2000, 'delta sem mudanças deve ser minúsculo');
  assert.ok(
    cursorBytes < fullBytes / 100,
    'delta incremental precisa ser pelo menos 100x menor que a leitura completa'
  );
}

  console.log('sync delta tests passed');
}

void main().catch((error) => {
  console.error(error);
  process.exit(1);
});
