const { test, expect } = require('@playwright/test');

test.use({ baseURL: 'http://localhost:3000' });
test.describe.configure({ timeout: 120000 });

const subject = {
  id: 'trainer-math',
  userId: 'trainer-user',
  name: 'Matematica Financeira',
  color: '#00B4FF',
  icon: 'calculator',
  priority: 8,
  difficulty: 7,
  targetHours: 4,
  completedHours: 0,
  totalHours: 0,
  sessionsCount: 0,
  averageScore: 0,
  isActive: true,
  createdAt: '2026-05-18T00:00:00.000Z',
  updatedAt: '2026-05-18T00:00:00.000Z',
};

const block = {
  id: 'trainer-block-1',
  userId: 'trainer-user',
  subjectId: subject.id,
  subject,
  date: '2026-05-18T00:00:00.000Z',
  startTime: '08:00',
  endTime: '08:50',
  durationMinutes: 50,
  status: 'scheduled',
  isBreak: false,
  isAutoGenerated: true,
  type: 'EXERCICIOS',
  sessionType: 'pratica',
  description: 'Lista de exercicios + revisar erros',
  createdAt: '2026-05-18T00:00:00.000Z',
  updatedAt: '2026-05-18T00:00:00.000Z',
};

test('trainer dashboard awards XP once and persists reward state', async ({ page }) => {
  const consoleProblems = [];
  page.on('console', (msg) => {
    const text = msg.text();
    if ((msg.type() === 'error' || msg.type() === 'warning') && !/favicon|DEP0205|sticky|scroll-behavior/i.test(text)) {
      consoleProblems.push(`${msg.type()}: ${text}`);
    }
  });

  await page.addInitScript(({ subjectSeed, blockSeed }) => {
    if (window.localStorage.getItem('__trainer_seeded') === 'true') return;
    window.localStorage.clear();
    window.localStorage.setItem('__trainer_seeded', 'true');
    window.localStorage.setItem('nexora_theme', 'dark');
    window.localStorage.setItem('nexora_demo_session', 'true');
    window.localStorage.setItem(
      'nexora_demo_user',
      JSON.stringify({ email: 'qa@nexora.local', name: 'Estudante QA' })
    );
    window.localStorage.setItem(
      'nexora_user_settings',
      JSON.stringify({
        name: 'Estudante QA',
        email: 'qa@nexora.local',
        dailyGoalHours: 1,
        preferredStart: '08:00',
        preferredEnd: '12:00',
        maxBlockMinutes: 50,
        breakMinutes: 10,
        excludeDays: [],
        aiDifficulty: 'adaptive',
        focusMode: false,
        autoSchedule: true,
        smartBreaks: true,
        dailyReminder: true,
        streakReminder: true,
        achievementAlerts: true,
        weeklyReport: true,
        notificationsEnabled: false,
        notificationMinutesBefore: 15,
        notificationSoundEnabled: false,
        backlogReminderEnabled: false,
        allowSundayBacklog: false,
        dailyHoursByWeekday: {
          dom: 0,
          seg: 50 / 60,
          ter: 1,
          qua: 1,
          qui: 1,
          sex: 1,
          sab: 0,
        },
      })
    );
    window.localStorage.setItem('nexora_subjects', JSON.stringify([subjectSeed]));
    window.localStorage.setItem('nexora_planner_blocks', JSON.stringify([blockSeed]));
    window.localStorage.setItem(
      'nexora_study_prefs',
      JSON.stringify({
        hoursPerDay: 50 / 60,
        daysOfWeek: [1, 2, 3, 4, 5],
        mode: 'exam',
        goal: 'concurso',
        focusBlockMinutes: 50,
        blockDurationMinutes: 50,
        breakDurationMinutes: 10,
      })
    );
    window.localStorage.setItem('nexora_analytics', JSON.stringify({ daily: {} }));
    window.localStorage.setItem(
      'nexora_onboarding',
      JSON.stringify({ hasCompletedWelcome: true, hasCompletedTutorial: true })
    );
    window.localStorage.setItem('nexora_xp_events', JSON.stringify([]));
    window.localStorage.setItem('nexora_unlocked_achievements', JSON.stringify([]));
  }, { subjectSeed: subject, blockSeed: block });

  await page.goto('/dashboard', { waitUntil: 'domcontentloaded' });
  await expect(page.getByText(/Seu treinador inteligente de estudos/i)).toBeVisible();
  await expect(page.getByText(/Próxima missão de estudo/i)).toBeVisible();
  await expect(page.getByRole('button', { name: /Começar agora/i })).toBeVisible();

  await page.getByRole('button', { name: /Começar agora/i }).click();
  await expect(page.getByText(/XP estimado:\s*\+35/i)).toBeVisible();
  await page.locator('.app-modal-panel').getByRole('button', { name: /^Iniciar$/i }).last().click();
  await page.getByRole('button', { name: /Concluir agora/i }).click();
  await expect(page.getByText(/Missão concluída/i)).toBeVisible();
  await expect(page.getByText('XP recebido', { exact: true })).toBeVisible();

  const persisted = await page.evaluate(() => ({
    events: JSON.parse(window.localStorage.getItem('nexora_xp_events') || '[]'),
    achievements: JSON.parse(window.localStorage.getItem('nexora_unlocked_achievements') || '[]'),
    blocks: JSON.parse(window.localStorage.getItem('nexora_planner_blocks') || '[]'),
  }));

  const totalXp = persisted.events.reduce((sum, event) => sum + event.amount, 0);
  expect(persisted.events.length).toBeGreaterThanOrEqual(2);
  expect(new Set(persisted.events.map((event) => event.eventKey)).size).toBe(persisted.events.length);
  expect(persisted.achievements.some((achievement) => achievement.achievementId === 'first-study')).toBe(true);
  expect(persisted.blocks[0].status).toBe('completed');

  await page.getByRole('button', { name: /Continuar/i }).click();
  await page.reload({ waitUntil: 'domcontentloaded' });
  await expect(page.getByRole('heading', { name: 'Missões de hoje', exact: true })).toBeVisible();
  await expect(page.getByText('Concluída', { exact: true })).toBeVisible();
  await expect(page.getByText(new RegExp(`\\+${totalXp}`))).toBeVisible();

  expect(consoleProblems).toEqual([]);
});
