const { test, expect } = require('@playwright/test');

test.use({ baseURL: 'http://localhost:3000' });
test.describe.configure({ timeout: 180000 });

const MS_DAY = 24 * 60 * 60 * 1000;

const dateKey = (date) =>
  `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(
    date.getDate()
  ).padStart(2, '0')}`;

const parseDateKey = (value) => {
  const [year, month, day] = value.split('-').map(Number);
  return new Date(year, month - 1, day);
};

const timeToMinutes = (value) => {
  const [hours, minutes] = value.split(':').map(Number);
  return hours * 60 + minutes;
};

const minutesToTime = (value) =>
  `${String(Math.floor(value / 60)).padStart(2, '0')}:${String(value % 60).padStart(2, '0')}`;

const addDays = (date, days) => {
  const next = new Date(date);
  next.setDate(next.getDate() + days);
  next.setHours(0, 0, 0, 0);
  return next;
};

const makeSubject = (partial) => {
  const now = new Date('2025-05-16T12:00:00');
  return {
    userId: 'user1',
    icon: 'book',
    priority: 5,
    difficulty: 5,
    targetHours: 60,
    completedHours: 0,
    totalHours: 0,
    sessionsCount: 0,
    averageScore: 0,
    isActive: true,
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
    ...partial,
  };
};

const subjects = [
  makeSubject({ id: 'portugues', name: 'Portugues (Interpretacao)', color: '#00B4FF', area: 'Linguagens', priority: 5, difficulty: 6, pesoNoExame: 5 }),
  makeSubject({ id: 'redacao', name: 'Redacao', color: '#00FFC8', area: 'Linguagens', priority: 5, difficulty: 7, pesoNoExame: 5 }),
  makeSubject({ id: 'literatura', name: 'Literatura', color: '#9B7CFF', area: 'Linguagens', priority: 3, difficulty: 4, pesoNoExame: 3 }),
  makeSubject({ id: 'ingles', name: 'Ingles/Espanhol', color: '#FF62B0', area: 'Linguagens', priority: 3, difficulty: 4, pesoNoExame: 3 }),
  makeSubject({ id: 'artes', name: 'Artes', color: '#FFB020', area: 'Linguagens', priority: 2, difficulty: 3, pesoNoExame: 2 }),
  makeSubject({ id: 'tec', name: 'Tecnologias da Comunicacao', color: '#00A8A8', area: 'Linguagens', priority: 2, difficulty: 3, pesoNoExame: 2 }),
  makeSubject({ id: 'matematica', name: 'Matematica', color: '#7F00FF', area: 'Matematica', priority: 5, difficulty: 8, pesoNoExame: 5 }),
  makeSubject({ id: 'fisica', name: 'Fisica', color: '#00B4FF', area: 'Natureza', priority: 4, difficulty: 7, pesoNoExame: 4 }),
  makeSubject({ id: 'quimica', name: 'Quimica', color: '#00FFC8', area: 'Natureza', priority: 4, difficulty: 6, pesoNoExame: 4 }),
  makeSubject({ id: 'biologia', name: 'Biologia', color: '#7F00FF', area: 'Natureza', priority: 4, difficulty: 6, pesoNoExame: 4 }),
  makeSubject({ id: 'historia', name: 'Historia', color: '#FF5555', area: 'Humanas', priority: 3, difficulty: 5, pesoNoExame: 3 }),
  makeSubject({ id: 'geografia', name: 'Geografia', color: '#FFB020', area: 'Humanas', priority: 3, difficulty: 5, pesoNoExame: 3 }),
  makeSubject({ id: 'filosofia', name: 'Filosofia', color: '#9B7CFF', area: 'Humanas', priority: 2, difficulty: 4, pesoNoExame: 2 }),
  makeSubject({ id: 'sociologia', name: 'Sociologia', color: '#00A8A8', area: 'Humanas', priority: 2, difficulty: 4, pesoNoExame: 2 }),
];

function buildSeed() {
  const start = new Date('2025-05-16T00:00:00');
  const today = new Date('2026-05-16T00:00:00');
  const futureEnd = new Date('2026-05-30T00:00:00');
  const blocks = [];
  const analytics = { daily: {} };
  const sessionHistory = [];
  const typeCycle = ['AULA', 'EXERCICIOS', 'REVISAO', 'AULA', 'EXERCICIOS'];
  let subjectIndex = 0;
  let blockIndex = 0;

  for (let cursor = new Date(start); cursor <= futureEnd; cursor = addDays(cursor, 1)) {
    const weekday = cursor.getDay();
    const isPast = cursor < today;
    const isFuture = cursor >= today;
    const allowed = weekday >= 1 && weekday <= 6;
    if (!allowed) continue;

    const dayStart = weekday === 6 ? '08:00' : '18:30';
    const dailyStudyBlocks = weekday === 6 ? 5 : 4;
    let minutes = timeToMinutes(dayStart);
    let studiedMinutes = 0;
    let sessions = 0;

    if (isFuture && blockIndex % 9 === 0) {
      blocks.push({
        id: `orphan-break-${blockIndex}`,
        userId: 'user1',
        subjectId: 'break',
        date: cursor.toISOString(),
        startTime: minutesToTime(minutes),
        endTime: minutesToTime(minutes + 10),
        durationMinutes: 10,
        status: 'scheduled',
        isBreak: true,
        isAutoGenerated: true,
        createdAt: cursor.toISOString(),
        updatedAt: cursor.toISOString(),
      });
      minutes += 10;
    }

    for (let i = 0; i < dailyStudyBlocks; i += 1) {
      const subject = subjects[subjectIndex % subjects.length];
      const duration = i % 3 === 0 ? 40 : 50;
      const type = typeCycle[(blockIndex + i) % typeCycle.length];
      const startTime = minutesToTime(minutes);
      const endTime = minutesToTime(minutes + duration);
      const completedAt = isPast ? new Date(cursor.getTime() + (minutes + duration) * 60000) : null;
      const totalQuestions = type === 'EXERCICIOS' ? 20 + (blockIndex % 8) : undefined;
      const correctAnswers = totalQuestions ? Math.max(4, Math.round(totalQuestions * (0.52 + ((blockIndex % 30) / 100)))) : undefined;

      blocks.push({
        id: `study-${blockIndex}`,
        userId: 'user1',
        subjectId: subject.id,
        subject,
        date: cursor.toISOString(),
        startTime,
        endTime,
        durationMinutes: duration,
        status: isPast ? 'completed' : 'scheduled',
        type,
        sessionType: type === 'EXERCICIOS' ? 'pratica' : type === 'REVISAO' ? 'revisao' : 'teoria',
        description: type === 'EXERCICIOS' ? 'Lista de exercicios + revisar erros' : type === 'REVISAO' ? 'Revisao guiada com flashcards' : 'Aula + anotacoes + resumo',
        isBreak: false,
        isAutoGenerated: true,
        originalDate: cursor.toISOString(),
        completedAt: completedAt ? completedAt.toISOString() : undefined,
        correctAnswers,
        totalQuestions,
        pedagogicalStepIndex: (blockIndex % 4) + 1,
        pedagogicalStepTotal: 4,
        rescheduleCount: 0,
        createdAt: cursor.toISOString(),
        updatedAt: completedAt ? completedAt.toISOString() : cursor.toISOString(),
      });

      if (isPast) {
        studiedMinutes += duration;
        sessions += 1;
        if (sessionHistory.length < 500) {
          sessionHistory.push({
            blockId: `study-${blockIndex}`,
            subjectId: subject.id,
            date: completedAt.toISOString(),
            minutes: duration,
            type,
            correctAnswers,
            totalQuestions,
          });
        }
      }

      blockIndex += 1;
      subjectIndex += 1;
      minutes += duration;

      if (i < dailyStudyBlocks - 1) {
        blocks.push({
          id: `break-${blockIndex}-${i}`,
          userId: 'user1',
          subjectId: 'break',
          date: cursor.toISOString(),
          startTime: minutesToTime(minutes),
          endTime: minutesToTime(minutes + 10),
          durationMinutes: 10,
          status: isPast ? 'completed' : 'scheduled',
          isBreak: true,
          isAutoGenerated: true,
          createdAt: cursor.toISOString(),
          updatedAt: cursor.toISOString(),
        });
        minutes += 10;
      }
    }

    if (isPast) {
      const key = dateKey(cursor);
      analytics.daily[key] = {
        hours: Number((studiedMinutes / 60).toFixed(2)),
        sessions,
        correctAnswers: 48 + (blockIndex % 30),
        totalQuestions: 80,
        accuracyRate: Number((0.55 + ((blockIndex % 20) / 100)).toFixed(2)),
      };
    }
  }

  const completedBySubject = new Map();
  blocks
    .filter((block) => !block.isBreak && block.status === 'completed')
    .forEach((block) => {
      completedBySubject.set(block.subjectId, (completedBySubject.get(block.subjectId) || 0) + block.durationMinutes);
    });

  const hydratedSubjects = subjects.map((subject) => {
    const minutes = completedBySubject.get(subject.id) || 0;
    return {
      ...subject,
      completedHours: Number((minutes / 60).toFixed(2)),
      totalHours: Number((minutes / 60).toFixed(2)),
      sessionsCount: Math.round(minutes / 45),
      averageScore: 58 + (minutes % 30),
    };
  });

  return {
    summary: {
      period: `${dateKey(start)} a ${dateKey(today)}`,
      futureSeedUntil: dateKey(futureEnd),
      subjects: hydratedSubjects.length,
      studyBlocks: blocks.filter((block) => !block.isBreak).length,
      completed: blocks.filter((block) => !block.isBreak && block.status === 'completed').length,
      scheduledFuture: blocks.filter((block) => !block.isBreak && block.status !== 'completed').length,
      breaks: blocks.filter((block) => block.isBreak).length,
      totalHours: Number((blocks.filter((block) => !block.isBreak).reduce((sum, block) => sum + block.durationMinutes, 0) / 60).toFixed(1)),
      sessionHistory: sessionHistory.length,
    },
    storage: {
      nexora_demo_session: 'true',
      nexora_demo_user: { email: 'teste@nexora.local', name: 'Estudante Teste' },
      nexora_subjects: hydratedSubjects,
      nexora_planner_blocks: blocks,
      nexora_analytics: analytics,
      nexora_session_timers: {},
      nexora_schedule_range: { startDate: dateKey(start), endDate: dateKey(futureEnd) },
      nexora_daily_limits: {
        '2026-05-18': 999,
        '2026-05-19': 450,
        '2026-05-20': 390,
      },
      nexora_first_cycle_all_subjects: true,
      nexora_study_prefs: {
        hoursPerDay: 4,
        daysOfWeek: [1, 2, 3, 4, 5, 6],
        mode: 'balanced',
        goal: 'enem',
        intensity: 'normal',
        blockDurationMinutes: 50,
        breakDurationMinutes: 10,
      },
      nexora_user_settings: {
        name: 'Estudante Teste',
        email: 'teste@nexora.local',
        theme: 'light',
        preferredStart: '18:30',
        preferredEnd: '22:40',
        maxBlockMinutes: 60,
        breakMinutes: 10,
        autoSchedule: true,
        smartBreaks: true,
        focusMode: false,
        aiDifficulty: 'medium',
        notificationsEnabled: false,
        notificationMinutesBefore: 15,
        notificationSoundEnabled: false,
        backlogReminderEnabled: false,
        allowSundayBacklog: false,
        dailyHoursByWeekday: {
          dom: 0,
          seg: 4,
          ter: 4,
          qua: 4,
          qui: 4,
          sex: 4,
          sab: 4.5,
        },
        dailyAvailabilityByWeekday: {
          dom: { start: '09:00', end: '09:00' },
          seg: { start: '18:30', end: '22:40' },
          ter: { start: '18:30', end: '22:40' },
          qua: { start: '18:30', end: '22:40' },
          qui: { start: '18:30', end: '22:40' },
          sex: { start: '18:30', end: '22:40' },
          sab: { start: '08:00', end: '12:30' },
        },
      },
    },
  };
}

function countOrphanBreaks(blocks) {
  const byDay = new Map();
  for (const block of blocks) {
    const key = dateKey(new Date(block.date));
    const list = byDay.get(key) || [];
    list.push(block);
    byDay.set(key, list);
  }

  let count = 0;
  for (const dayBlocks of byDay.values()) {
    const studyBlocks = dayBlocks
      .filter((block) => !block.isBreak && block.status !== 'skipped')
      .sort((a, b) => timeToMinutes(a.startTime) - timeToMinutes(b.startTime));

    for (const block of dayBlocks) {
      if (!block.isBreak || block.status === 'completed' || block.status === 'in-progress') continue;
      if (block.isAutoGenerated === false) continue;
      const start = timeToMinutes(block.startTime);
      const end = start + block.durationMinutes;
      const previous = [...studyBlocks].reverse().find((study) => timeToMinutes(study.startTime) + study.durationMinutes <= start);
      const next = studyBlocks.find((study) => timeToMinutes(study.startTime) >= end);
      const anchored =
        previous &&
        next &&
        Math.abs(timeToMinutes(previous.startTime) + previous.durationMinutes - start) <= 1 &&
        end <= timeToMinutes(next.startTime);
      if (!anchored) count += 1;
    }
  }
  return count;
}

async function readStorage(page) {
  return page.evaluate(() => {
    const parse = (key, fallback) => {
      try {
        return JSON.parse(window.localStorage.getItem(key) || JSON.stringify(fallback));
      } catch {
        return fallback;
      }
    };
    return {
      blocks: parse('nexora_planner_blocks', []),
      subjects: parse('nexora_subjects', []),
      dailyLimits: parse('nexora_daily_limits', {}),
      sessionTimers: parse('nexora_session_timers', {}),
      storageBytes: new Blob(Object.values(window.localStorage)).size,
    };
  });
}

async function pageHealth(page, path) {
  const started = Date.now();
  await page.goto(path, { waitUntil: 'networkidle' });
  const bodyText = await page.locator('body').innerText().catch(() => '');
  const badTextMatch = bodyText.match(/undefined|NaN|Invalid Date|\[object Object\]/i);
  const badTextIndex = badTextMatch ? Math.max(0, badTextMatch.index - 40) : -1;
  return {
    path,
    elapsed: Date.now() - started,
    badText: Boolean(badTextMatch),
    badTextSnippet:
      badTextIndex >= 0
        ? bodyText.slice(badTextIndex, badTextIndex + 140).replace(/\s+/g, ' ')
        : '',
    visibleError: /Application error|Unhandled Runtime Error|TypeError|ReferenceError/i.test(bodyText),
    chars: bodyText.length,
  };
}

test('one-year student audit', async ({ page, context }) => {
  const consoleProblems = [];
  page.on('console', (msg) => {
    const text = msg.text();
    if ((msg.type() === 'error' || msg.type() === 'warning') && !/favicon|DEP0205/i.test(text)) {
      consoleProblems.push(`${msg.type()}: ${text}`);
    }
  });
  page.on('pageerror', (error) => consoleProblems.push(`pageerror: ${error.message}`));

  const auth = { loginOk: false, invalidLoginBlocked: false, logoutOk: false, authProblems: [] };
  await page.goto('/login', { waitUntil: 'networkidle' });
  await page.locator('input[name="email"]').fill('email-invalido');
  await page.locator('input[name="password"]').fill('');
  await page.locator('form button[type="submit"]').click();
  auth.invalidLoginBlocked = await page.getByText(/e-mail valido|email valido/i).isVisible().catch(() => false);

  await page.locator('input[name="email"]').fill('teste@nexora.local');
  await page.locator('input[name="password"]').fill('teste1234');
  await page.locator('form button[type="submit"]').click();
  await page.waitForURL(/dashboard|planner|subjects|analytics|settings/, { timeout: 15000 });
  auth.loginOk = /dashboard|planner|subjects|analytics|settings/.test(page.url());

  const seed = buildSeed();
  await page.evaluate((storage) => {
    window.localStorage.clear();
    for (const [key, value] of Object.entries(storage)) {
      window.localStorage.setItem(key, typeof value === 'string' ? value : JSON.stringify(value));
    }
  }, seed.storage);

  await page.goto('/planner', { waitUntil: 'networkidle' });
  await expect(page.getByText(/Agenda de Estudos/)).toBeVisible({ timeout: 15000 });
  await page.waitForTimeout(1800);

  const checks = [];
  for (const path of ['/dashboard', '/planner', '/subjects', '/analytics', '/settings']) {
    checks.push(await pageHealth(page, path));
  }

  const responsive = [];
  for (const viewport of [
    { width: 390, height: 844, label: 'celular' },
    { width: 768, height: 1024, label: 'tablet' },
    { width: 1366, height: 768, label: 'desktop' },
  ]) {
    await page.setViewportSize({ width: viewport.width, height: viewport.height });
    const started = Date.now();
    await page.goto('/planner', { waitUntil: 'networkidle' });
    await page.waitForTimeout(1000);
    const bodyText = await page.locator('body').innerText().catch(() => '');
    const layout = await page.evaluate(() => ({
      bodyOverflow: document.documentElement.scrollWidth > window.innerWidth + 8,
      bodyHeight: document.body.scrollHeight,
    }));
    responsive.push({
      ...viewport,
      elapsed: Date.now() - started,
      badText: /undefined|NaN|Invalid Date|\[object Object\]/i.test(bodyText),
      visibleError: /Application error|Unhandled Runtime Error|TypeError|ReferenceError/i.test(bodyText),
      bodyOverflow: layout.bodyOverflow,
    });
  }

  await page.setViewportSize({ width: 1366, height: 768 });
  await page.goto('/planner', { waitUntil: 'networkidle' });
  await page.waitForTimeout(1200);
  const plannerTextBefore = await page.locator('body').innerText();
  const beforeStorage = await readStorage(page);
  const beforeFirstDates = beforeStorage.blocks
    .filter((block) => !block.isBreak && block.status !== 'completed')
    .slice(0, 8)
    .map((block) => `${dateKey(new Date(block.date))} ${block.startTime}`);

  const increaseButton = page.getByRole('button', { name: /Aumentar.*mater/i }).first();
  await increaseButton.click();
  await page.waitForTimeout(1200);
  const afterIncrease = await readStorage(page);
  const afterIncreaseDates = afterIncrease.blocks
    .filter((block) => !block.isBreak && block.status !== 'completed')
    .slice(0, 8)
    .map((block) => `${dateKey(new Date(block.date))} ${block.startTime}`);

  const decreaseButton = page.getByRole('button', { name: /Diminuir.*mater/i }).first();
  await decreaseButton.click();
  await page.waitForTimeout(1200);
  const afterDecrease = await readStorage(page);

  await page.getByRole('button', { name: /Adicionar estudo/i }).first().click();
  await page.locator('#study-block-start').fill('23:30');
  await page.locator('#study-block-duration').fill('120');
  await page.locator('form button[type="submit"]').click();
  const invalidBlocked = await page.getByText(/meia-noite|precisa ficar|duracao/i).isVisible().catch(() => false);
  await page.keyboard.press('Escape').catch(() => undefined);

  await page.goto('/planner', { waitUntil: 'networkidle' });
  await page.waitForTimeout(800);
  const startStudyButton = page.locator('button[aria-label="Iniciar estudo"]').first();
  await startStudyButton.click({ timeout: 10000 });
  await page.getByRole('button', { name: /^Iniciar$/ }).click();
  await page.waitForTimeout(300);
  await page.getByRole('button', { name: /Concluir agora/i }).click();
  await page.waitForTimeout(900);
  const afterComplete = await readStorage(page);
  const completionOk = afterComplete.blocks.some((block) => block.status === 'completed' && !block.id.startsWith('study-'));
  const completedAnyFuture = afterComplete.blocks.some(
    (block) => !block.isBreak && block.status === 'completed' && new Date(block.date) >= parseDateKey('2026-05-16')
  );

  await page.getByRole('button', { name: /Abrir sess/i }).first().click();
  const quickOpen = await page.getByText(/Configure e comece/i).isVisible().catch(() => false);
  await page.keyboard.press('Escape').catch(() => undefined);

  await page.goto('/subjects', { waitUntil: 'networkidle' });
  await page.getByRole('button', { name: /Adicionar Disciplina/i }).first().click();
  await page.locator('#subject-name').fill('Materia longa para testar quebra visual '.repeat(5));
  await page.locator('#subject-priority').fill('4');
  await page.locator('#subject-difficulty').fill('6');
  await page.locator('#subject-target-hours').fill('12');
  await page.locator('form button[type="submit"]').click();
  await page.waitForTimeout(600);
  const subjectAdded = (await readStorage(page)).subjects.some((subject) => subject.name.startsWith('Materia longa'));

  const secondTab = await context.newPage();
  await secondTab.goto('/subjects', { waitUntil: 'networkidle' });
  await secondTab.evaluate(() => {
    const raw = window.localStorage.getItem('nexora_subjects');
    const subjects = raw ? JSON.parse(raw) : [];
    if (subjects[0]) {
      subjects[0] = { ...subjects[0], name: 'Sincronizacao entre abas' };
      window.localStorage.setItem('nexora_subjects', JSON.stringify(subjects));
    }
  });
  await page.waitForTimeout(600);
  const multiTabSyncOk = await page
    .locator('body')
    .innerText()
    .then((text) => /Sincronizacao entre abas/.test(text))
    .catch(() => false);
  await secondTab.close();

  await page.reload({ waitUntil: 'networkidle' });
  const afterReload = await readStorage(page);
  const persistenceOk = afterReload.blocks.length > 0 && afterReload.subjects.some((subject) => subject.name.startsWith('Materia longa'));

  await page.goto('/settings', { waitUntil: 'networkidle' });
  const settingsOk = await page.getByText(/Ajustes|Configuracoes|Configura/i).first().isVisible().catch(() => false);

  await page.goto('/analytics', { waitUntil: 'networkidle' });
  const analyticsBodyText = await page.locator('body').innerText().catch(() => '');
  const analyticsOk = await page.getByText(/Desempenho|Análises|Analises|Horas|Sessões|Sessoes/i).first().isVisible().catch(() => false);

  await page.goto('/planner', { waitUntil: 'networkidle' });
  const finalStorage = await readStorage(page);
  const plannerTextAfter = await page.locator('body').innerText();

  await page.getByRole('button', { name: /Sair da conta/i }).click();
  await page.waitForURL(/login/, { timeout: 10000 }).catch(() => undefined);
  auth.logoutOk = /login/.test(page.url());

  const report = {
    summary: {
      ...seed.summary,
      storageMB: Number((finalStorage.storageBytes / 1024 / 1024).toFixed(2)),
    },
    auth,
    checks,
    responsive,
    interactions: {
      plannerSummaryOk:
        /Estudo:/.test(plannerTextBefore) &&
        /Meta:/.test(plannerTextBefore) &&
        /Ocupado:/.test(plannerTextBefore) &&
        /Janela:/.test(plannerTextBefore) &&
        !/Capacidade:/.test(plannerTextAfter),
      orphanBreaksBeforeRepair: countOrphanBreaks(seed.storage.nexora_planner_blocks),
      orphanBreaksAfterRepair: countOrphanBreaks(finalStorage.blocks),
      futureLimits: finalStorage.dailyLimits,
      invalidBlocked,
      reflowChanged: JSON.stringify(beforeFirstDates) !== JSON.stringify(afterIncreaseDates),
      afterDecreaseBlocks: afterDecrease.blocks.length,
      completionOk: completedAnyFuture || completionOk,
      quickOpen,
      subjectAdded,
      multiTabSyncOk,
      persistenceOk,
      settingsOk,
      analyticsOk,
      analyticsText: analyticsBodyText.slice(0, 160).replace(/\s+/g, ' '),
    },
    consoleProblems: consoleProblems.slice(0, 10),
    failed: [],
  };

  for (const [key, value] of Object.entries(report.interactions)) {
    if (key.startsWith('orphanBreaks')) continue;
    if (value === false) report.failed.push(key);
  }
  if (!report.auth.loginOk || !report.auth.logoutOk || !report.auth.invalidLoginBlocked) {
    report.failed.push('auth');
  }
  if (report.interactions.orphanBreaksAfterRepair !== 0) report.failed.push('orphanBreaksAfterRepair');
  if (
    report.consoleProblems.some((entry) =>
      /Maximum update depth|Cannot update a component|controlled input|TypeError|ReferenceError|pageerror/i.test(entry)
    )
  ) {
    report.failed.push('consoleProblems');
  }
  if (checks.some((check) => check.badText || check.visibleError)) report.failed.push('pageHealth');
  if (responsive.some((item) => item.badText || item.visibleError || item.bodyOverflow)) report.failed.push('responsive');

  console.log(JSON.stringify(report, null, 2));
  expect(report.failed).toEqual([]);
});
